export {default as serviceImg1} from "./idea.png"
export {default as serviceImg2} from "./population.png"
export {default as serviceImg3} from "./analytics.png"
export {default as serviceImg4} from "./growth.png"
export {default as serviceImg5} from "./branding.png"
export {default as ClientReviewImg} from "./clientReviewImg1.jpg" 
export {default as ClientImg} from "./clintImg.jpg" 